Add Rev AI support
nkkko/sapat pull request #1
Opened 2024-08-19 22:02 UTC by giraffekey

Add support for Rev AI based on the "Contribute to the repo to add more supported APIs" instruction in: https://github.com/daytonaio/content/issues/13

I wasn't sure how to interpret the instruction, so let me know if I misinterpreted and if you want any other APIs added.

2024-08-20 12:35 UTC, nkkko commented
Could you please add OpenAI and Groq as written in the related issue. Thanks.

2024-08-21 22:07 UTC, giraffekey commented
Done.

2024-08-28 07:50 UTC, nkkko requested changes
Hi, thanks but I can't get it working for some reason. Have you tested it? Could you please update .env.example with prefilled values for standard fields besides the api keys.

2024-08-28 07:50 UTC, nkkko commented on script.py
> +OPENAI_ENDPOINT = os.getenv('OPENAI_ENDPOINT')
do you need this? Have you tested it?

2024-08-28 07:50 UTC, nkkko commented on script.py
> +OPENAI_MODEL_CHAT = os.getenv('OPENAI_MODEL_CHAT')
openai_model is whisper-1?

2024-08-28 07:50 UTC, nkkko commented on script.py
> +GROQ_OPENAI_ENDPOINT = os.getenv('GROQ_OPENAI_ENDPOINT')
what are the values for endpoint, could you please enter examples in .env.example

2024-08-28 07:50 UTC, nkkko commented on script.py
> +OPENAI_MODEL_CHAT = os.getenv('OPENAI_MODEL_CHAT')
what are the values for endpoint, could you please enter examples in .env.example

2025-01-15 21:37 UTC, closed without merging